### PR TITLE
Fixed for the issues with disk size and swap size

### PR DESCRIPTION
**Pull request by a-lang**
- Fixed for multiple disks not showing correct size.
 - Fixed for non-english system can't detect the SWAP.

### CODE REVIEW

**Comment by L1so** [comment]
Can you tell me what do you mean by "not showing correct size" ? Because the command works fine on all my setup.
```bash
$ df -k -t ext2 -t ext3 -t ext4 -t btrfs -t xfs -t vfat -t ntfs -t swap --total | grep "^total"
total           33969808 12431500  19791948  39% -
$ df -k /
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/vda2       33969808 12431500  19791948  39% /
```

**Comment by a-lang** [comment]
If you got two disks as follows.
```
root@silicloud-us-8GB:~# df -k -t ext2 -t ext3 -t ext4 -t btrfs -t xfs -t vfat -t ntfs -t swap --total
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/vda1        9974088  4706124   5251580  48% /
/dev/vdb1       71669880  6002712  61980820   9% /my_app
/dev/vda15        106858     5313    101545   5% /boot/efi
total           81750826 10714149  67333945  14% -
```

**Comment by a-lang** [comment]
Sorry for missing this
```
root@silicloud-us-8GB:~# df -k /
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/vda1        9974088 4706140   5251564  48% /
```

**Comment by L1so** [comment]
> If you got two disks as follows.
> 
> ```
> root@silicloud-us-8GB:~# df -k -t ext2 -t ext3 -t ext4 -t btrfs -t xfs -t vfat -t ntfs -t swap --total
> Filesystem     1K-blocks     Used Available Use% Mounted on
> /dev/vda1        9974088  4706124   5251580  48% /
> /dev/vdb1       71669880  6002712  61980820   9% /my_app
> /dev/vda15        106858     5313    101545   5% /boot/efi
> total           81750826 10714149  67333945  14% -
> ```

What happen when you omit the `-t type` ? Is there any special reason you have to specify filesystem beforehand ?

**Comment by a-lang** [comment]
If you omitted the -t
```
root@silicloud-us-8GB:~# df -k 
Filesystem     1K-blocks    Used Available Use% Mounted on
udev             4056868       0   4056868   0% /dev
tmpfs             814868    1460    813408   1% /run
/dev/vda1        9974088 4706312   5251392  48% /
tmpfs            4074336       0   4074336   0% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
tmpfs            4074336       0   4074336   0% /sys/fs/cgroup
/dev/vdb1       71669880 6002712  61980820   9% /my_app
/dev/loop0         50816   50816         0 100% /snap/snapd/17883
/dev/vda15        106858    5313    101545   5% /boot/efi
/dev/loop1         94080   94080         0 100% /snap/lxd/23991
/dev/loop4         64768   64768         0 100% /snap/core20/1695
/dev/loop3         63488   63488         0 100% /snap/core20/1518
overlay          9974088 4706312   5251392  48% /var/lib/docker/overlay2/724785b774f22011f20998088810aedbb5e4596b9c9af696e2e6eab5f445a294/merged
tmpfs             814864       0    814864   0% /run/user/0
overlay          9974088 4706312   5251392  48% /var/lib/docker/overlay2/020f17fa517aa97dabeea55ef128565e936178f64cfd4058951940eb22f8328f/merged
overlay          9974088 4706312   5251392  48% /var/lib/docker/overlay2/b3c5da8f1aba68a476035a6ba39349f0be3f5a5becd9ca2cc15a65495219347d/merged
overlay          9974088 4706312   5251392  48% /var/lib/docker/overlay2/b5390e71517b7ef6dfd5fd8b7fa1fb5dbbe3b187ace249cd4d6b57001165edf4/merged
overlay          9974088 4706312   5251392  48% /var/lib/docker/overlay2/42c80927bf37d0bd42eab6ff2d46d97ef52168179199dac9267685998b623f63/merged
overlay          9974088 4706312   5251392  48% /var/lib/docker/overlay2/293d02d1a5d6ad9203e85081bee0b8a01c0183d75d879a0f978a4857322d367e/merged
/dev/loop5         94080   94080         0 100% /snap/lxd/24061
```

**Comment by L1so** [comment]
Hello, I just pushed a fix similar to you-- but I'm using `awk` to exclude unwanted filesystem and to parse it result. Can you try it ?
```bash
wget -qO- benchy.pw/dev | sh -s -- -pk
```
Does this looks okay to you ? I have test this with my Pi which have multiple disk.

Before:
```bash
# # # # # # # # # # # # # # # # # # # # #
#             Benchy v2.4               #
#    https://github.com/L1so/benchy     #
# # # # # # # # # # # # # # # # # # # # #
#        06 Dec 2022 11:54 WIB          #
# # # # # # # # # # # # # # # # # # # # #

Server Insight                                  Hardware Information
---------------------                           ---------------------
OS         : Debian GNU/Linux 11 (bullseye)     Model       : Cortex-A53
Location   : Indonesia                          Core        : 4 @ 1400 MHz
Kernel     : 5.10.92-v8+                        AES-NI      : ❌ Disabled
Uptime     : 40 days, 21 hrs, 44 mins, 11 secs  VM-x/AMD-V  : ❌ Disabled
Virt       : none                               Swap        : 100.0 MiB 

Disk & Memory Usage                             Network Information
---------------------                           ---------------------
Disk       : 29.1 GiB                           ASN         : AS63859   
Disk Usage : 8.4 GiB (31% Used)                 ISP         : PT. Eka Mas Republik
Mem        : 909.9 MiB                          IPv4        : ✔ Enabled
Mem Usage  : 0.4 GiB (47% Used)                 IPv6        : ❌ Disabled
```
After:
```bash
# # # # # # # # # # # # # # # # # # # # #
#             Benchy v2.4               #
#    https://github.com/L1so/benchy     #
# # # # # # # # # # # # # # # # # # # # #
#        06 Dec 2022 11:55 WIB          #
# # # # # # # # # # # # # # # # # # # # #

Server Insight                                  Hardware Information
---------------------                           ---------------------
OS         : Debian GNU/Linux 11 (bullseye)     Model       : Cortex-A53
Location   : Indonesia                          Core        : 4 @ 1400 MHz
Kernel     : 5.10.92-v8+                        AES-NI      : ❌ Disabled
Uptime     : 40 days, 21 hrs, 44 mins, 47 secs  VM-x/AMD-V  : ❌ Disabled
Virt       : none                               Swap        : 100.0 MiB 

Disk & Memory Usage                             Network Information
---------------------                           ---------------------
Disk       : 1.8 TiB                            ASN         : AS63859   
Disk Usage : 1.2 TiB (64% Used)                 ISP         : PT. Eka Mas Republik
Mem        : 909.9 MiB                          IPv4        : ✔ Enabled
Mem Usage  : 0.4 GiB (47% Used)                 IPv6        : ❌ Disabled
```

**Comment by a-lang** [comment]
It looks fine.
```
root@silicloud-us-8GB:~# wget -qO- benchy.pw/dev | sh -s -- -pk
# # # # # # # # # # # # # # # # # # # # #
#             Benchy v2.4               #
#    https://github.com/L1so/benchy     #
# # # # # # # # # # # # # # # # # # # # #
#        06 Dec 2022 11:19 UTC          #
# # # # # # # # # # # # # # # # # # # # #

Server Insight                                  Hardware Information
---------------------                           ---------------------
OS         : Ubuntu 20.04.5 LTS                 Model       : Intel(R) Xeon(R) Platinum 8251 CPU @ 3.80
Location   : United States                      Core        : 2 @ 3791.076 MHz
Kernel     : 5.4.0-132-generic                  AES-NI      : ✔ Enabled
Uptime     : 5 days, 22 hrs, 8 mins, 37 secs    VM-x/AMD-V  : ❌ Disabled
Virt       : kvm                                Swap        : 0.0 KiB   

Disk & Memory Usage                             Network Information
---------------------                           ---------------------
Disk       : 78.0 GiB                           ASN         : AS149042  
Disk Usage : 10.2 GiB (13% Used)                ISP         : SICLOUD INFORMATION TECHNOLOGY (HONGKONG)..
Mem        : 7.8 GiB                            IPv4        : ✔ Enabled
Mem Usage  : 2.6 GiB (33% Used)                 IPv6        : ✔ Enabled
```

**Comment by L1so** [comment]
Gonna close this PR, the script can handle multiple disk properly now.

**Pull request closed without merging**
